# Generated by Django 5.1.9 on 2025-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onexweb', '0002_remove_novel_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='genre',
            new_name='genres',
        ),
    ]
