# Generated by Django 5.1.9 on 2025-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onexweb', '0003_rename_genre_novel_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus'), ('dropped', 'Dropped')], default='ongoing', max_length=50),
        ),
    ]
