# Generated by Django 5.1.9 on 2025-05-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onexweb', '0004_alter_novel_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('novel', 'chapter_number')},
        ),
    ]
