# Generated by Django 5.1.9 on 2025-05-27 02:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onexweb', '0005_alter_chapter_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('novel', 'user')},
        ),
    ]
