# Generated by Django 5.1.9 on 2025-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onexweb', '0007_alter_novel_authors_alter_novel_genres'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['name'], name='onexweb_nov_name_e7af48_idx'),
        ),
    ]
